server:
  port: 8080

spring:
  application:
    name: registro-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  discovery:
    enabled: true
  cloud:
    feign:
      hystrix:
        enabled: true
